-- ALTER TABLE AspNetUsers ADD NormalizedUserName NVARCHAR(256)
-- ALTER TABLE AspNetUsers ADD ConcurrencyStamp NVARCHAR(256)
-- ALTER TABLE AspNetUsers ADD LockoutEnd NVARCHAR(256)
-- ALTER TABLE AspNetUsers ADD NormalizedEmail NVARCHAR(256)